export type WinInvoice = {
  lotId: string;
  title: string;
  slug?: string | null;
  currentBid: number;
  premium: number;
  handling: number;
  shippingCost: number;
  gst: number;
  total: number;
  status?: string;
  invoice: string;
  paymentMethod: string;
  paymentMethodKey: "helcim_card";
  instructions: string;
  winning: boolean;
  fulfillment: "unset" | "ship" | "pickup";
  address: string;
  buyerName: string;
  phone: string;
  paid: boolean;
  paidAt?: string | null;
  payment?: "unpaid" | "partial" | "paid" | "cash_pending";
  paymentChannel?: "helcim" | "cash";
};
